instablog/urls.py
from django.conf.urls import url
from django.contrib import admin

#from blog.views import hello
#from blog.views import hello_with_template
#from blog.views import list_posts
from blog import views as blog_views

urlpatterns = [
    #url(r'^$', hello),
    url(r'^posts/create/$',blog_views.create_post, name = 'create_post'),
    url(r'^posts/(?P<pk>[0-9]+)/$', blog_views.view_post, name='view_post'),
    url(r'^posts/(?P<pk>[0-9]+)/delete/$', blog_views.delete_post, name='delete_post'),
    url(r'^posts/(?P<pk>[0-9]+)/delete_comment/(?P<pk2>[0-9]+)/$', blog_views.delete_comment, name='delete_comment'),
    url(r'^$', blog_views.list_posts, name = 'list_posts'),
    url(r'^admin/', admin.site.urls),
    #url(r'^$', hello),
    #url(r'', hello),
    url(r'^hello', blog_views.hello_with_template),

]

blog/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
	name = models.CharField(max_length=40)
	#def __str__(self):
	#	return '{} 번째 카테고리명 : {}'.format(self.pk, self.name)


class Post(models.Model):
	# blog_post (appname_dbname)
	title = models.CharField(max_length=200)
	contents = models.TextField()
	tags = models.ManyToManyField('Tag')
	category = models.ForeignKey(Category, null = True)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	
	is_model_field = False

	def __str__(self):
		return '<{}>'.format(self.pk)
		# return '{}-{}-{}'.format(self.pk, self.title, self.contents)

class Comment(models.Model):
	post = models.ForeignKey(Post)
	content = models.TextField(max_length=500)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

	#def __str__(self):
	#	return '{}글의 {}번 댓글 - 내용 : {}'.format(self.post_id, self.id, self.content)

class Tag(models.Model):
	name = models.CharField(max_length=40)
	#def __str__(self):
	#	return '{}의 {} 태그'.format(self.post_id, self.name)

blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

from django.http import HttpResponse
from django.core.paginator import Paginator
from django.core.paginator import PageNotAnInteger
from django.core.paginator import EmptyPage

from .models import Post
from .models import Comment
from .models import Category


def hello(request):
	return HttpResponse('hello world')

def hello_with_template(request):
	return render(request, 'hello.html')

def list_posts(request):
	per_page = 3
	current_page = request.GET.get('page',1)
	# current_page = int(request.GET['page']) 숫자를 문자열로 받아요
	#try:
		#current_page = int(request.GET['page'])
		#page인자 없는 것 대응
	#	current_page = int(request.GET.get('page',1))
	#except ValueError:
	#	current_page = 1

	all_posts = Post.objects.select_related().all().order_by('-pk')
	
	pagi = Paginator(all_posts, per_page)

	try:
		pg = pagi.page(current_page)
	except PageNotAnInteger:
		pg = pagi.page(1)
	except EmptyPage:
		pg = []

	#all_posts = all_posts[(current_page-1)*per_page:current_page*per_page]
	return render(request, 'list_posts.html', {
		'posts':pg,
		})

# 댓글 생성하기 전 버전
# def view_post(request, pk):
# 	# try execption하던가 
# 	the_post = get_object_or_404(Post, pk=pk)

# 	#the_post = Post.objects.get(pk=pk)
# 	return render(request, 'view_posts.html', {
# 		'post': the_post,

# 		})

# 댓글 추가 버전 
def view_post(request, pk):
	# try execption하던가 
	the_post = get_object_or_404(Post, pk=pk)

	if request.method == 'GET':
		pass
	elif request.method == 'POST':
		new_comment = Comment()
		new_comment.content = request.POST.get('content')
		new_comment.post_id = pk
		new_comment.save()
		return redirect('view_post', pk=pk)

	#the_post = Post.objects.get(pk=pk)
	return render(request, 'view_posts.html', {
		'post': the_post,

		})


def create_post(request):
	categories = Category.objects.all()
	if request.method == 'GET':
		pass
	elif request.method == 'POST':
		new_post = Post()
		new_post.title = request.POST.get('title')
		new_post.content = request.POST.get('content')

		category_pk = request.POST.get('category')
		category = get_object_or_404(Category, pk = category_pk)
		new_post.category = category
		new_post.save()

		return redirect('view_post', pk=new_post.pk)

	return render(request, 'create_post.html', {
		'categories':categories,
		})

def delete_post(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == 'POST':
		#post.delete()
		return redirect('/')

	return render(request, 'delete_post.html',{
		'post':post,
		})

def delete_comment(request, pk, pk2):
	if request.method == 'GET':
		comment = get_object_or_404(Comment, pk=pk2)
		comment.delete()
		return redirect('view_post', pk)

blog/templates/blog_layout.html
{% load bootstrap3 %}
<!DOCTYPE html>
<!-- blog/templates/blog_layout.html -->
<html>
	<head>
		<meta charset = "UTF-8">
		<title> {% block page_title %} 인스타블로그 {% endblock %} </title>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
		
		{% bootstrap_css %}
		{% bootstrap_javascript %}
		
	</head>

	<body class = "container">
		
		{% block content %} {% endblock %}

	</body>


</html>

blog/templates/create_post.html
{% extends 'blog_layout.html' %}
{% load bootstrap3 %}

<!-- blog/templates/list_posts.html -->
{% block page_title %} 글 작성 {% endblock %}


{% block content %}
	<form method="POST" action="">
		{% csrf_token %}
		<p>


            <select name="category">
            {% for category in categories %}
            <option value="{{ category.pk }}">{{ category.name }}</option>
            {% endfor %}
            </select>


		</p>

		<p>
		<label for="id_title"> 글 제목 </label>
		<input type="text" name="title" id = "id_title"/>
		</p>

		<p>
		<textarea name="content"></textarea>
		</p>

		<p>
		<button type = "submit">저장</button>
		</p>
	</form>
{% endblock %}

blog/templates/delete_comment.html
{% extends 'blog_layout.html' %}
{% load bootstrap3 %}

{% block page_title %} {{post.pk}} 번째 글 삭제 확인 : {{post.title}}{% endblock %}

{% block content %}
		
	<form method="POST" action ="">
		{% csrf_token %}
		
		<h3> 글 제목 : {{post.title}} </a></h3>

		<div class = 'post_content'>
			글 내용 : 
			<p>
				{{post.contents}}
			</p>

		</div>

		<div>
			<p> 글 갈래 : {{post.category.name}}</p>
			<p> 작성일시 : {{post.created_at}}</p>
		</div>	

		<p>
			정말로 지우시겠습니까?
		</p>
		<p>
			<button type="submit">삭제</button>
		</p>
	</form>

{% endblock %}

blog/templates/delete_post.html
{% extends 'blog_layout.html' %}
{% load bootstrap3 %}

{% block page_title %} {{post.pk}} 번째 글 삭제 확인 : {{post.title}}{% endblock %}

{% block content %}
		
	<form method="POST" action ="">
		{% csrf_token %}
		
		<h3> 글 제목 : {{post.title}} </a></h3>

		<div class = 'post_content'>
			글 내용 : 
			<p>
				{{post.contents}}
			</p>

		</div>

		<div>
			<p> 글 갈래 : {{post.category.name}}</p>
			<p> 작성일시 : {{post.created_at}}</p>
		</div>	

		<p>
			정말로 지우시겠습니까?
		</p>
		<p>
			<button type="submit">삭제</button>
		</p>
	</form>

{% endblock %}

blog/templates/hello.html
<html>
	<head>
		<title> hello world </title>
		<meta charset="UTF-8">
	</head>

	<body>
		반갑습니다!
	</body>
</html>

blog/templates/list_posts.html
{% extends 'blog_layout.html' %}
{% load bootstrap3 %}

<!-- blog/templates/list_posts.html -->
{% block page_title %} 글 LIST  {% endblock %}


{% block content %}

		{% for post in posts %}

		<div class = 'post_container'>
			<h3><a href="{% url 'view_post' pk=post.pk %}">{{ post.title }}</a></h3>

			<div class = 'post_content'>
				{{post.contents}}
			</div>

			<div>
				<p> 글 갈래 : {{post.category.name}}</p>
				<p> 작성일시 : {{post.created_at}}</p>
				<p> 댓글 수 : {{post.comment_set.count}} </p>
			</div>

		</div>
		{% empty %}
		<p> 글이 전혀 없습니다. </p>

		{% endfor %}

		{% bootstrap_pagination posts %}
{% endblock %}

blog/templates/view_posts.html
{% extends 'blog_layout.html' %}
{% load bootstrap3 %}

{% block page_title %} {{post.pk}} 번째 글 보기 : {{post.title}}{% endblock %}

{% block content %}
		
	<div class = 'post_container'>
		<h3> <a href="/posts/{{post.pk}}/">{{post.title}} </a></h3>

		<div class = 'post_content'>
			{{post.contents}}
		</div>

		<div>
			<p> 글 갈래 : {{post.category.name}}</p>
			<p> 작성일시 : {{post.created_at}}</p>
		</div>

		{# <h5> <a href="/">글 삭제 </a></h5> #}
		<a class="btn btn-default" href="/posts/{{post.pk}}/delete"> 글 삭제 </a>
		<a class="btn btn-default" href="/"> 리스트 이동  </a>

		<!-- commet 보여주기 -->
		<hr/>
		
		{% for comment in post.comment_set.all %}

		<div class = 'comment_container'>
			<!-- 몇 번 째 comment인지 계산 어떻게 구현하는지... 실패 --> 
			<h5> {{comment}}번째 댓글</h5>

			<div class = 'comment_content'>
				{{comment.content}}
			</div>

			<div>
				<p> 작성일시 : {{comment.created_at}}</p>
			</div>

			<a href ="/posts/{{post.pk}}/delete_comment/{{comment.pk}}"> 삭제 </a>

		</div>
		{% empty %}
		<p> 댓글이 전혀 없습니다. </p>

		{% endfor %}
		
	</div>

<!-- 댓굴 추가 부분 -->
	<form method="POST" action="">
		{% csrf_token %}

		<p>
		<textarea name="content"></textarea>
		</p>

		<p>
		<button type = "submit">댓글 저장</button>
		</p>
	</form>



{% endblock %}